### ISSUE TITLE
Zod type ZodNonEmptyArray is unsupported by OpenAPI

### ISSUE THREAD

**Issue by kirdk** [RobinTail/express-zod-api#98] opened 2021-08-14 12:35 UTC
If output uses `z.array().notempty`, Open API won't start with the message `Zod type ZodNonEmptyArray is unsupported`
`ZodUndefined` also does not work
express-zod-api version is `2.3.0`

**Comment by RobinTail** [comment] 2021-08-14 15:30
Hello @kirdk .

Thank you for the feedback.

> `z.array().notempty`

I presume you mean `z.array(...).nonempty()`. In this case I can not reproduce the issue in `v2.3.0`, it works with a following result
```yaml
schema:
  type: array
  items:
    type: ...
  minItems: 1
```

Could you please provide more context or code sample for me to reproduce the issue.


> `ZodUndefined` also does not work

I didn't expect this to be used given that there is `.optional()` refinement, but I'll add it, no problem.

Thank you

**Comment by kirdk** [comment] 2021-08-17 10:07
D

> Hello @kirdk .
> 
> Thank you for the feedback.
> 
> > `z.array().notempty`
> 
> I presume you mean `z.array(...).nonempty()`. In this case I can not reproduce the issue in `v2.3.0`, it works with a following result
> 
> ```yaml
> schema:
>   type: array
>   items:
>     type: ...
>   minItems: 1
> ```
> 
> Could you please provide more context or code sample for me to reproduce the issue.
> 
> > `ZodUndefined` also does not work
> 
> I didn't expect this to be used given that there is `.optional()` refinement, but I'll add it, no problem.
> 
> Thank you

Dear @RobinTail, I have checked again with v. 2.3.1 and the issue is the same. The problem appears when the response schema contains a ZodNonEmptyArray.
![image](https://user-images.githubusercontent.com/12613557/129705449-b01935ce-908a-4841-b66b-4a5a1083633a.png)

Regarding ZodUndefined. In some cases, it's useful to implement subTypes. Because if we define the subtypes something like:
`
const Base = z.object({ id: z.string() });
const SubType1 = Base.extend({ field1: z.string() });
const SubType2 = Base.extend({ field2: z.string() });
const Type = z.union([SubType1, SubType2]);
type Type = z.infer<typeof Type>;
`
We can have a compilation error:
![image](https://user-images.githubusercontent.com/12613557/129706295-d0af6254-65cf-46ac-aa76-f61db0230952.png)
But if we define the schema like:
`
const Base = z.object({ id: z.string() });
const SubType1 = Base.extend({ field1: z.string(), field2: z.undefined() });
const SubType2 = Base.extend({ field1: z.undefined(), field2: z.string() });
const Type = z.union([SubType1, SubType2]);
type Type = z.infer<typeof Type>;
`
We don't have such a problem:
![image](https://user-images.githubusercontent.com/12613557/129706703-71e2bf6c-6d2c-4f15-8ca7-43925cf125f9.png)

**Comment by RobinTail** [comment] 2021-08-17 16:11
>  The problem appears when the response schema contains a ZodNonEmptyArray.

May I ask you for a code sample to reproduce this issue?
@kirdk

**Comment by RobinTail** [comment] 2021-08-17 19:01
@kirdk, Regarding the situation around ZodUndefined.

I figured out that there is no need for using ZodUndefined in order to resolve your issue with ZodUnion.
The only thing you need is the right syntax for the type narrowing within `if` condition.
Please see this PR with a detailed description, example and tests: 

https://github.com/RobinTail/express-zod-api/pull/104

**Comment by RobinTail** [comment] 2021-08-18 21:37
@kirdk , Regarding `ZodNonEmptyArray` issue.

I figured out that there is no such class in Zod 3.7.x, though it existed in 3.6.x.
But `express-zod-api` is using 3.7.1 since version 2.1.0.

The fact that you are experiencing this issue with the latest version of `express-zod-api` might mean that for some reason you have incorrect version of Zod installed as the `express-zod-api` dependency.

Please check out this PR with a test that covers the `z.array().nonempty()` case, additional information and recommendations:

https://github.com/RobinTail/express-zod-api/pull/105

**Comment by RobinTail** [comment] 2021-08-18 22:34
@kirdk , please upgrade to version 2.3.2 I've just released and make sure that your package manager installs Zod version 3.7.2  as the dependency.
I believe this should fix your issue with ZodNonEmptyArray.

Use `if ('field' in object)` type narrowing syntax instead of ZodUndefined.
I believe this should fix your issue with ZodUnion.

I'm closing this issue. In case your issue persist please open another one with detailed code samples.
Thank you for your feedback.

**Closed by RobinTail** 2021-08-18 22:34 UTC
Labels: not an issue

**Comment by kirdk** [comment] 2021-08-20 19:15
> @kirdk , Regarding `ZodNonEmptyArray` issue.
> 
> I figured out that there is no such class in Zod 3.7.x, though it existed in 3.6.x.
> But `express-zod-api` is using 3.7.1 since version 2.1.0.
> 
> The fact that you are experiencing this issue with the latest version of `express-zod-api` might mean that for some reason you have incorrect version of Zod installed as the `express-zod-api` dependency.
> 
> Please check out this PR with a test that covers the `z.array().nonempty()` case, additional information and recommendations:
> 
> #105

Dear @RobinTail , while we prepared a project to reproduce the issue you solved it). I do confirm that problem was in zod dependency. After the update, the issue is solved.

**Comment by kirdk** [comment] 2021-08-20 19:25
> @kirdk , please upgrade to version 2.3.2 I've just released and make sure that your package manager installs Zod version 3.7.2 as the dependency.
> I believe this should fix your issue with ZodNonEmptyArray.
> 
> Use `if ('field' in object)` type narrowing syntax instead of ZodUndefined.
> I believe this should fix your issue with ZodUnion.
> 
> I'm closing this issue. In case your issue persist please open another one with detailed code samples.
> Thank you for your feedback.

@RobinTail, using 'in' is not an elegant solution, because the whole code should be wrapped just because we using one union with an optional field. We already wrapping the access to the field value, because it can be undefined. Additional wrapping just to get it works with Openapi it's not awesome :-) Thanks anyway! We will try to reopen the issue after the project deadline and prepare a sample.
