### ISSUE TITLE
Type error when using custom server

### ISSUE THREAD

**Issue by Isaac-Leonard** [RobinTail/express-zod-api#749] opened 2022-12-18 09:18 UTC
I get this error when using a custom express instance:
Argument of type '{ app: Express; }' is not assignable to parameter of type '(AppConfig | ServerConfig) & CommonConfig<string>'.
  Type '{ app: Express; }' is not assignable to type 'AppConfig & CommonConfig<string>'.
    Type '{ app: Express; }' is missing the following properties from type 'CommonConfig<string>': cors, logger [2345]

**Comment by RobinTail** [comment] 2022-12-18 12:44
Well, the error says exactly what you're missing: `cors` and `logger` options.

Try this:

```ts
// const app = express(); // your custom express app
const config = createConfig({ 
  app,
  cors: true,
  logger: { level: "debug", color: true },
});
```

, @Isaac-Leonard

**Comment by RobinTail** [comment] 2022-12-21 20:00
@Isaac-Leonard , is the issue resolved?

**Comment by RobinTail** [comment] 2022-12-23 11:11
I hope it's resolved.
I'm going to close it, but in case the issue is not resolved by the clarification above, please open another one.

**Closed by RobinTail** 2022-12-23 11:11 UTC

**Comment by Isaac-Leonard** [comment] 2022-12-30 07:53
Hi sorry, yes I was able to solve it easily after creating this issue, the main thing now is to update the docs as I believe my code was pretty much copied and pasted from them.
