### ISSUE TITLE
Bug: Cannot use `dateIn` as an input for a middleware

### ISSUE THREAD

**Issue by shroudedcode** [RobinTail/express-zod-api#673] opened 2022-10-28 15:23 UTC
Another small bug my team discovered:

Right now, it's not possible to define a middleware with a `dateIn` input. Calling an endpoint using such a middleware always results in a `<field_name>: Expected string, received date` error.

I didn't have time to look into the source code here, but it seems like inputs might be parsed/validated multiple times (once at the middleware and then again at the endpoint), and by the time they're checked for the second time the date string has already been parsed to a date (which is not the expected input type of `dateIn`). Could that be the case?

**Comment by RobinTail** [comment] 2022-10-28 15:29
@shroudedcode , `dateIn` is a transformation schema, that receives `string` and provides the handler with the `Date` instead. The error you're receiving is the correct behavior that is caused by the way you're testing the endpoint.
Somehow you in your test you managed to pass `Date` to inputs, which is not possible in normal circumstances, since inputs are collected from the `Request` properties, that are either query params (strings) or `.body`, which is `JSON`, that does not support `Date`. 
Please ensure passing `string` timestamp in your test.

**Comment by RobinTail** [comment] 2022-10-28 15:41
@shroudedcode 
When testing the endpoint, you pass the `requestProps`.
These props emulate the `Request` properties AFTER `express` does the initial JSON parsing.
So, for instance `.body` should be the object that `JSON.parse()` can produce.
Perhaps I should clarify this better in Readme.

```ts
import { testEndpoint } from "express-zod-api";

const { responseMock } = await testEndpoint({
  endpoint,
  requestProps: {
    method: "POST",
    body: {
      dateParam: "2022-09-28T00:00:00.000Z" // <—
    },
  },
});
```

**Comment by RobinTail** [comment] 2022-10-28 15:46
I'm going to improve the documentation according to this issue.

**Comment by RobinTail** [comment] 2022-10-28 16:06
Ok, thank you for the code sample. I will check it soon, @shroudedcode

**Comment by RobinTail** [comment] 2022-10-28 16:35
Confirmed, @shroudedcode .
The problem is causes by double parsing.
Thank you very much for finding this.
I'll do my best to fix this ASAP.

**Comment by RobinTail** [comment] 2022-10-28 17:44
@shroudedcode , the fix will be released today.

**Closed** 2022-10-28 17:43 UTC
Labels: bug

**Comment by RobinTail** [comment] 2022-10-28 17:56
🚀  the patch v8.3.2 is released 
Thank you again for noticing this.
